language: go
go:
  - 1.7.x
sudo: required
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y btrfs-tools libdevmapper-dev
install: ./scripts/travis.sh install
script:
  - ./scripts/travis.sh lint
  - ./scripts/travis.sh build
  - ./scripts/travis.sh test
